version: 0.2

env:
  shell: bash
  exported-variables:
    - REACT_APP_API_ENDPOINT
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Installing Dependencies
      - npm install
  build:
    commands:
      - echo Building
      - npm run build
  post_build:
    commands:
      - echo Zipping artifacts
      - cd build
      - zip -r ../build.zip *
        #
        # batch:
        #   fast-fail: true

artifacts:
  files:
    - build.zip