version: 0.2

env:
  shell: bash
  exported-variables:
    - REACT_APP_API_ENDPOINT
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre-build:
    commands:
      - echo Installing Dependencies
      - npm install
  build:
    commands:
      - echo Building
      - npm run build
        # post-build:
        #   commands:
        #     - echo Zipping artifacts
        #     - npm run build

artifacts:
  files:
    - build/**/*